# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  H_joint1:
#    has_velocity_limits: true
#    max_velocity: 0.98
#    has_acceleration_limits: true
#    max_acceleration: 1.96
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  H_joint2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  L_joint1:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_joint2:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_joint3:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_joint4:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_joint5:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_joint6:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_joint7:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_left_joint:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  L_right_joint:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint1:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint2:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint3:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint4:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint5:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint6:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_joint7:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_left_joint:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
  R_right_joint:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.5
