(cl:defpackage mr_msgs-msg
  (:use )
  (:export
   "<ASSEMBLYSTATE>"
   "ASSEMBLYSTATE"
   "<ASSEMBLYSTATES>"
   "ASSEMBLYSTATES"
   "<COLLISIONAVOIDANCESTATE>"
   "COLLISIONAVOIDANCESTATE"
   "<COLLISIONDETECTIONSTATE>"
   "COLLISIONDETECTIONSTATE"
   "<ENDEFFECTORCOMMAND>"
   "ENDEFFECTORCOMMAND"
   "<ENDEFFECTORPROPERTIES>"
   "ENDEFFECTORPROPERTIES"
   "<ENDEFFECTORSTATE>"
   "ENDEFFECTORSTATE"
   "<ENDPOINTSTATE>"
   "ENDPOINTSTATE"
   "<ENDPOINTSTATES>"
   "ENDPOINTSTATES"
   "<GRIPPERCOMMAND>"
   "GRIPPERCOMMAND"
   "<GRIPPERSTATE>"
   "GRIPPERSTATE"
   "<JOINTCOMMAND>"
   "JOINTCOMMAND"
  ))

